### ISSUE TITLE
`PaymentPayload` type is missing `status_code`

### ISSUE THREAD

**Issue by chloehjung15** [akahu-io/akahu-sdk-js#44]
https://github.com/akahu-io/akahu-sdk-js/blob/953f4d2fb71baa16c8afbc2c72e9b24880f559ee/src/models/webhooks.ts#L142

`status_code` is missing from `PaymentPayload` type here

**Comment by dabrowne** [comment]
Hi @chloehjung15 thanks for creating this issue. We've now published `akahu@1.15.1` with a fix.
